@server=http://localhost:4004
@username=alice
@password=


### Coletas
# @name Coletas_GET
GET {{server}}/odata/v4/catalog/Coletas
Authorization: Basic {{username}}:{{password}}


### Coletas
# @name Coletas_POST
POST {{server}}/odata/v4/catalog/Coletas
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31220396-3379-4cf4-8803-5fb2e305b8a4",
  "cnpj_fornecedor": "cnpj_fornecedor-31220395",
  "transportadora": "transportadora-31220396",
  "pedidos": [],
  "acompanhamento": [
    {
      "data_comentario": "2011-03-06T00:00:00.000Z",
      "status": {
        "status": "Coletada"
      }
    }
  ],
  "createdAt": "2023-11-06T00:00:00.000Z",
  "createdBy": "createdBy.il5t8@example.org",
  "modifiedAt": "2010-04-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.il5t8@example.net"
}


### Coletas
# @name Coletas_PATCH
PATCH {{server}}/odata/v4/catalog/Coletas/31220396-3379-4cf4-8803-5fb2e305b8a5
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31220396-3379-4cf4-8803-5fb2e305b8a5",
  "cnpj_fornecedor": "cnpj_fornecedor-31220396",
  "transportadora": "transportadora-31220396",
  "pedidos": [
    {
      "numero_pedido": "Pedidos-30218802",
      "item_pedido": "Pedidos-30218802",
      "valor_pedido": 31.17
    },
    {
      "numero_pedido": "Pedidos-30218803",
      "item_pedido": "Pedidos-30218803",
      "valor_pedido": 87.53
    }
  ],
  "acompanhamento": [
    {
      "data_comentario": "2011-03-06T00:00:00.000Z",
      "status": {
        "status": "Coletada"
      }
    }
  ],
  "createdAt": "2023-11-06T00:00:00.000Z",
  "createdBy": "createdBy.il5t8@example.org",
  "modifiedAt": "2010-04-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.il5t8@example.net"
}


### Coletas
# @name Coletas_DELETE
DELETE {{server}}/odata/v4/catalog/Coletas/31220396-3379-4cf4-8803-5fb2e305b8a5
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Pedidos
# @name Pedidos_GET
GET {{server}}/odata/v4/catalog/Pedidos
Authorization: Basic {{username}}:{{password}}


### Pedidos
# @name Pedidos_POST
POST {{server}}/odata/v4/catalog/Pedidos
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "numero_pedido": "Pedidos-30218802",
  "item_pedido": "Pedidos-30218802",
  "valor_pedido": 31.17
}


### Pedidos
# @name Pedidos_PATCH
PATCH {{server}}/odata/v4/catalog/Pedidos(numero_pedido='Pedidos-30218802',item_pedido='Pedidos-30218802')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "numero_pedido": "Pedidos-30218802",
  "item_pedido": "Pedidos-30218802",
  "valor_pedido": 31.17
}


### Pedidos
# @name Pedidos_DELETE
DELETE {{server}}/odata/v4/catalog/Pedidos(numero_pedido='Pedidos-30218802',item_pedido='Pedidos-30218802')
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Acompanhamentos
# @name Acompanhamentos_GET
GET {{server}}/odata/v4/catalog/Acompanhamentos
Authorization: Basic {{username}}:{{password}}


### Acompanhamentos
# @name Acompanhamentos_POST
POST {{server}}/odata/v4/catalog/Acompanhamentos
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "data_comentario": "2011-03-06T00:00:00.000Z",
  "status": {
    "status": "Coletada"
  }
}


### Acompanhamentos
# @name Acompanhamentos_PATCH
PATCH {{server}}/odata/v4/catalog/Acompanhamentos/[object Object]
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "data_comentario": "2011-03-06T00:00:00.000Z",
  "status": {
    "status": "Coletada"
  }
}


### Acompanhamentos
# @name Acompanhamentos_DELETE
DELETE {{server}}/odata/v4/catalog/Acompanhamentos/[object Object]
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Status
# @name Status_GET
GET {{server}}/odata/v4/catalog/Status
Authorization: Basic {{username}}:{{password}}


### Status
# @name Status_POST
POST {{server}}/odata/v4/catalog/Status
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "status": "Coletada",
  "descricao": "descricao-17591676"
}


### Status
# @name Status_PATCH
PATCH {{server}}/odata/v4/catalog/Status/Coletada
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "status": "Coletada",
  "descricao": "descricao-17591676"
}


### Status
# @name Status_DELETE
DELETE {{server}}/odata/v4/catalog/Status/Coletada
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
